routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// DB::listen(function($query){
// 	echo "<pre>{$query->sql}</pre>";
// });

// Route::get('job', function() {
//     dispatch(new App\Jobs\SendEmail);
//     return 'Listo!';
// });

// Route::get('{URL}'), ['as' => '{NOMBRE}', function () {
Route::get('/', ['as' => 'home', 'uses' => 'PagesController@home']);
Route::get('createuser', ['as' => 'createuser', 'uses' => 'PagesController@createuser']);
Route::get('home', 'PagesController@home');
Route::get('saludos/{nombre?}', ['as' => 'saludo', 'uses' => 'PagesController@saludo'])->where('nombre', "[A-Za-z]+");
Route::resource('mensajes', 'MessagesController');
Route::resource('usuarios', 'UsersController');
// Route::get('login', 'Auth\LoginController@showLoginForm');
Route::get('login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
Route::post('login', ['as' => 'iniciarsesion', 'uses' => 'Auth\LoginController@login']);
Route::get('logout', ['as' => 'cerrarsesion', 'uses' => 'Auth\LoginController@logout']);

// Route::get('mensajes/create', ['as' => 'messages.create', 'uses' => 'MessagesController@create']);
// Route::post('mensajes', ['as' => 'messages.store', 'uses' => 'MessagesController@store']);
// Route::get('mensajes', ['as' => 'messages.index', 'uses' => 'MessagesController@index']);
// Route::get('mensajes/{id}', ['as' => 'messages.show', 'uses' => 'MessagesController@show']);
// Route::get('mensajes/{id}/edit', ['as' => 'messages.edit', 'uses' => 'MessagesController@edit']);
// Route::put('mensajes/{id}', ['as' => 'messages.update', 'uses' => 'MessagesController@update']);
// Route::delete('mensajes/{id}', ['as' => 'messages.destroy', 'uses' => 'MessagesController@destroy']);

resources/views/home.blade.php
@extends('layout')

@section('contenido')
<h1>Home</h1>
@stop

resources/views/layout.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Mi sitio Web</title>
	<link rel="stylesheet" href="/css/app.css">
	<script>
		window.Laravel = {
			csrfToken: "{{csrf_token()}}"
		}
	</script>
	<meta name="csrf-token" content="{{ csrf_token() }}">
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
		  	<a class="navbar-brand" href="#">Blog.test</a>
		  	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		    	<span class="navbar-toggler-icon"></span>
		  	</button>
		  	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		    	<ul class="navbar-nav mr-auto">
		      		<li class="nav-item {{ activeMenu(request()->is("/")) }}">
		        		<a class="nav-link" href="{{ route('home') }}">Inicio</a>
		      		</li>
		      		<li class="nav-item {{ activeMenu(request()->is("saludos/*")) }}">
		        		<a class="nav-link" href="{{ route('saludo', 'ale') }}">Saludos</a>
		      		</li>
		      		<li class="nav-item {{ activeMenu(request()->is("mensajes/create")) }}">
		        		<a class="nav-link" href="{{ route('mensajes.create') }}">Contáctenos</a>
		      		</li>
		      		@if(auth()->check())
		      		<li class="nav-item {{ activeMenu(request()->is("mensajes*")) }}">
						<a class="nav-link" href="{{ route('mensajes.index') }}">Mensajes</a>
					</li>
			      	@if(auth()->user()->hasRole(['admin']))
			      		<li class="nav-item {{ activeMenu(request()->is("usuarios*")) }}">
							<a class="nav-link" href="{{ route('usuarios.index') }}">Usuarios</a>
						</li>
			      	@endif
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						  {{ auth()->user()->name }}
						</a>
						<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						  {{-- <a class="dropdown-item" href="#">Action</a> --}}
						  <a class="dropdown-item" href="{{ route('usuarios.edit', auth()->id()) }}">Mi cuenta</a>
						  <div class="dropdown-divider"></div>
						  <a class="dropdown-item" href="{{route('cerrarsesion')}}">Cerrar sesión</a>
						</div>
					</li>
					@endif
		      		@if(auth()->guest())
		      		<li class="nav-item {{ activeMenu(request()->is("login")) }}">
						<a class="nav-link" href="{{route('login')}}">Login</a>
					</li>
					@endif
		    	</ul>
		  	</div>
		</nav>
	</header>
	<div class="container-fluid">
		@yield('contenido')
	</div>
	<hr>
	<footer>
		<div class="container-fluid">
			Copyright {{ date('Y') }}
		</div>
	</footer>
	<script type="text/javascript" src="/js/all.js"></script>
</body>
</html>

resources/views/saludo.blade.php
@extends('layout')

@section('contenido')
<h1>Saludo para {{ $nombre }}</h1>
<ul>
	@forelse($consolas as $consola)
		<li>{{ $consola }}</li>
	@empty
		<p>No hay consolas :(</p>
	@endforelse
</ul>
@if(count($consolas) === 1)
	<p>Solo tienes una consola</p>
@else
	<p>Tienes {{ count($consolas) }} consolas</p>
@endif
{!! $html !!}
<!-- {{ $script }} -->
<!-- {!! $script !!} -->
@stop