routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// DB::listen(function($query){
// 	echo "<pre>{$query->sql}</pre>";
// });

// Route::get('job', function() {
//     dispatch(new App\Jobs\SendEmail);
//     return 'Listo!';
// });

// Route::get('{URL}'), ['as' => '{NOMBRE}', function () {
Route::get('/', ['as' => 'home', 'uses' => 'PagesController@home']);
Route::get('createuser', ['as' => 'createuser', 'uses' => 'PagesController@createuser']);
Route::get('home', 'PagesController@home');
Route::get('saludos/{nombre?}', ['as' => 'saludo', 'uses' => 'PagesController@saludo'])->where('nombre', "[A-Za-z]+");
Route::resource('mensajes', 'MessagesController');
Route::resource('usuarios', 'UsersController');
// Route::get('login', 'Auth\LoginController@showLoginForm');
Route::get('login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
Route::post('login', ['as' => 'iniciarsesion', 'uses' => 'Auth\LoginController@login']);
Route::get('logout', ['as' => 'cerrarsesion', 'uses' => 'Auth\LoginController@logout']);

// Route::get('mensajes/create', ['as' => 'messages.create', 'uses' => 'MessagesController@create']);
// Route::post('mensajes', ['as' => 'messages.store', 'uses' => 'MessagesController@store']);
// Route::get('mensajes', ['as' => 'messages.index', 'uses' => 'MessagesController@index']);
// Route::get('mensajes/{id}', ['as' => 'messages.show', 'uses' => 'MessagesController@show']);
// Route::get('mensajes/{id}/edit', ['as' => 'messages.edit', 'uses' => 'MessagesController@edit']);
// Route::put('mensajes/{id}', ['as' => 'messages.update', 'uses' => 'MessagesController@update']);
// Route::delete('mensajes/{id}', ['as' => 'messages.destroy', 'uses' => 'MessagesController@destroy']);

app/User.php
<?php

namespace App;

use App\Presenter\UserPresenter;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * Esta función encrypta el password cuando se haga un update o insert a la tabla User
     */
    public function setPasswordAttribute($password) {
        $this->attributes['password'] = bcrypt($password);
    }

    /**
     * Esta función indica la relación con la tabla Roles
     */
    public function roles() {
        return $this->belongsToMany(Role::class, 'assigned_roles'); // 'assigned_roles' = Nombre de la tabla en la BD
    }

    public function hasRole(array $roles) {
        return $this->roles->pluck('name')->intersect($roles)->count();
        // ^
        // |
        // Esto es igual a esto
        //                  |
        //                  v
        // foreach ($roles as $role) {
        //     foreach ($this->roles as $userRole) {
        //         if ($userRole->name === $role) {
        //             return true;
        //         }
        //     }
        // }
        // return false;
    }

    public function isAdmin() {
        return $this->hasRole(['admin']);
    }

    public function messages() {
        return $this->hasMany(Message::class);
    }

    public function note() {
        return $this->morphOne(Note::class, 'notable');
    }

    public function tags() {
        return $this->morphToMany(tags::class, 'taggable')->withTimestamps();
    }

    public function present()
    {
        return new UserPresenter($this);
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\Role;
use App\User;
use Illuminate\Http\Request;
use App\Http\Requests\CreateuserRequest;
use App\Http\Requests\UpdateUserRequest;

class UsersController extends Controller
{
    public function __construct(){
        $this->middleware('auth', ['except' => ['show']]);
        $this->middleware('role:admin', ['except' => ['edit', 'update', 'show', 'destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::with(['roles', 'note', 'tags'])->get();
        return view('users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::pluck('display_name', 'id');

        // return view('users.edit', ['user' => $user]);
        return view('users.create', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\CreateUserRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateuserRequest $request)
    {
        $user = User::create($request->all());
        $user->roles()->attach($request->role);
        return redirect()
                    ->route('usuarios.index')
                    ->with('info', 'Usuario creado correctamente');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::findOrFail($id);
        return view('users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);

        $this->authorize($user);

        $roles = Role::pluck('display_name', 'id');

        // return view('users.edit', ['user' => $user]);
        return view('users.edit', compact('user', 'roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdateUserRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateUserRequest $request, $id)
    {
        $user = User::findOrFail($id);

        $this->authorize($user);

        $user->update($request->only('name', 'email'));
        $user->roles()->sync($request->role); // Asignamos los roles del request

        // Redireccionar
        return redirect()
                    ->route('usuarios.index')
                    ->with('info', 'Usuario modificado correctamente');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findOrFail($id);

        $this->authorize('destroy', $user);
        // dd($user);

        $user->messages()->delete();
        $user->roles()->detach();
        $user->delete();

        // Redireccionar
        return redirect()
                    ->route('usuarios.index')
                    ->with('info', 'Usuario eliminado correctamente');
    }
}

resources/views/users/create.blade.php
@extends('layout')

@section('contenido')
<h1>Crear usuario</h1>
<form method="post" action="{{route('usuarios.store')}}">
	@include('users.form', ['user' => new App\User])
	<input type="submit" class="btn btn-primary" value="Guardar">
</form>
@stop

resources/views/users/edit.blade.php
@extends('layout')

@section('contenido')
<h1>Editar usuario</h1>
<form method="post" action="{{route('usuarios.update', $user->id)}}">
	{{ method_field('PUT') }}
	@include('users.form')
	<input type="submit" class="btn btn-primary" value="Modificar">
</form>
@stop

resources/views/users/form.blade.php
{{-- Devuelve un input con el valor del _token --}}
{!! csrf_field() !!}
<p><label for="name">
	Nombre
	<input type="text" class="form-control" name="name" value="{{ $user->name ?? old('name') }}">
	{!! $errors->first('name', '<span class="p-1 mb-1 bg-danger text-white">:message</span>') !!}
</label></p>
<p><label for="email">
	Email
	<input type="text" class="form-control" name="email" value="{{ $user->email ?? old('email') }}">
	{!! $errors->first('email', '<span class="p-1 mb-1 bg-danger text-white">:message</span>') !!}
</label></p>
@unless ($user->id)
	<p><label for="password">
		Clave
		<input type="password" class="form-control" name="password" value="">
		{!! $errors->first('password', '<span class="p-1 mb-1 bg-danger text-white">:message</span>') !!}
	</label></p>
	<p><label for="password_confirmation">
		Confirmar clave
		<input type="password" class="form-control" name="password_confirmation" value="">
		{!! $errors->first('password_confirmation', '<span class="p-1 mb-1 bg-danger text-white">:message</span>') !!}
	</label></p>
@endunless
@foreach ($roles as $id => $role)
	<div class="form-group form-check">
	    <input type="checkbox" class="form-check-input" 
	    	name="role[]" 
	    	{{$user->roles->pluck('id')->contains($id) ? 'checked' : ''}}
	    	value="{{$id}}" 
	    	id="exampleCheck{{$id}}">
	    <label class="form-check-label" for="exampleCheck{{$id}}">{{$role}}</label>
	</div>
@endforeach
<p>{!! $errors->first('role', '<span class="p-1 mb-1 bg-danger text-white">:message</span>') !!}</p>

resources/views/users/index.blade.php
@extends('layout')

@section('contenido')

<h1>Lista de usuarios</h1>
@if(session()->has('info'))
	<div class="alert alert-success" role="alert">
	  	{{ session('info') }}
	</div>
@endif
<p><a class="btn btn-primary" href="{{route('usuarios.create')}}">Crear nuevo usuario</a></p>
@if(count($users) > 0)
	<table class="table">
		<tr>
			<td>ID</td>
			<td>Nombre</td>
			<td>Email</td>
			<td>Rol</td>
			<td>Notas</td>
			<td>Etiquetas</td>
			<td>Creado el</td>
			<td>Modificado el</td>
			<td>Acciones</td>
		</tr>
		@foreach($users as $user)
			<tr>
				<td>{{$user->id}}</td>
				<td>{{$user->present()->link()}}</td>
				<td>{{$user->email}}</td>
				<td>
					{{$user->present()->roles()}}
				</td>
				<td>{{$user->present()->notes()}}</td>
				<td>{{$user->present()->tags()}}</td>
				<td>{{$user->created_at}}</td>
				<td>{{$user->updated_at}}</td>
				<td>
					{{-- @if($user->role !== "admin") --}}
					<a class="btn btn-info btn-sm" href="{{ route('usuarios.edit', $user->id) }}">Editar</a>
					<form style="display: inline;" action="{{ route('usuarios.destroy', $user->id) }}" method="POST">
						{{method_field('DELETE')}}
						{{csrf_field()}}
						<input type="submit" class="btn btn-danger btn-sm" value="Eliminar">
					</form>
					{{-- @endif --}}
				</td>
			</tr>
		@endforeach
	</table>
@else
	<p>No hay mensajes guardados</p>
@endif

@stop

resources/views/users/show.blade.php
@extends('layout')

@section('contenido')

<h1>Usuario {{$user->name}}</h1>

<ul class="list-unstyled">
	<li><strong>Rol</strong>: 
		{{-- <ul class="list-inline"> --}}
			@foreach ($user->roles as $role)
				{{-- <li class="list-inline-item">{{$role->display_name}}</li> --}}
				{{$role->display_name}}
			@endforeach
		{{-- </ul> --}}
	</li>
	<li><strong>Email</strong>: <a href="mailto:{{$user->email}}">{{$user->email}}</a></li>
	<li><strong>Fecha creación</strong>: {{$user->created_at}}</li>
	<li><strong>Fecha modificación</strong>: {{$user->updated_at}}</li>
</ul>

@can('edit', $user)
	<a href="{{ route('usuarios.edit', $user->id) }}" class="btn btn-primary" role="button">Editar</a>
@endcan

@can('destroy', $user)
	<form style="display: inline;" action="{{ route('usuarios.destroy', $user->id) }}" method="POST">
		{{method_field('DELETE')}}
		{{csrf_field()}}
		<input type="submit" class="btn btn-danger" value="Eliminar">
	</form>
@endcan

@stop