routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// DB::listen(function($query){
// 	echo "<pre>{$query->sql}</pre>";
// });

// Route::get('job', function() {
//     dispatch(new App\Jobs\SendEmail);
//     return 'Listo!';
// });

// Route::get('{URL}'), ['as' => '{NOMBRE}', function () {
Route::get('/', ['as' => 'home', 'uses' => 'PagesController@home']);
Route::get('createuser', ['as' => 'createuser', 'uses' => 'PagesController@createuser']);
Route::get('home', 'PagesController@home');
Route::get('saludos/{nombre?}', ['as' => 'saludo', 'uses' => 'PagesController@saludo'])->where('nombre', "[A-Za-z]+");
Route::resource('mensajes', 'MessagesController');
Route::resource('usuarios', 'UsersController');
// Route::get('login', 'Auth\LoginController@showLoginForm');
Route::get('login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
Route::post('login', ['as' => 'iniciarsesion', 'uses' => 'Auth\LoginController@login']);
Route::get('logout', ['as' => 'cerrarsesion', 'uses' => 'Auth\LoginController@logout']);

// Route::get('mensajes/create', ['as' => 'messages.create', 'uses' => 'MessagesController@create']);
// Route::post('mensajes', ['as' => 'messages.store', 'uses' => 'MessagesController@store']);
// Route::get('mensajes', ['as' => 'messages.index', 'uses' => 'MessagesController@index']);
// Route::get('mensajes/{id}', ['as' => 'messages.show', 'uses' => 'MessagesController@show']);
// Route::get('mensajes/{id}/edit', ['as' => 'messages.edit', 'uses' => 'MessagesController@edit']);
// Route::put('mensajes/{id}', ['as' => 'messages.update', 'uses' => 'MessagesController@update']);
// Route::delete('mensajes/{id}', ['as' => 'messages.destroy', 'uses' => 'MessagesController@destroy']);

app/Message.php
<?php

namespace App;

use App\Presenter\MessagePresenter;
use Illuminate\Database\Eloquent\Model;

class Message extends Model
{
    // protected $table = "nombre_de_la_tabla"; // para cambiar el nombre de la tabla
    protected $fillable = ['nombre', 'email', 'mensaje']; // campos que Eloquent insertará desde Message::create() y Message:update(). Impide la asignación masiva de datos

    public function user() {
    	return $this->belongsTo(User::class);
    }

    public function note() {
    	return $this->morphOne(Note::class, 'notable');
    }

    public function tags() {
    	return $this->morphToMany(tags::class, 'taggable');
    }

    public function present()
    {
        return new MessagePresenter($this);
    }
}

app/Http/Controllers/MessagesController.php
<?php

namespace App\Http\Controllers;

use App\Message;
use Illuminate\Http\Request;
use App\Events\MessageWasReceived;
use App\Repositories\MessagesInterface;
use App\Http\Requests\CreateMessageRequest;

class MessagesController extends Controller
{
    protected $messages;

    public function __construct(MessagesInterface $messages){
        $this->messages = $messages;
        $this->middleware('auth', ['except' => ['create', 'store']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $messages = $this->messages->getPaginated();
        return view('messages.index', compact('messages'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // dd(config('services.sparkpost.secret'));
        return view('messages.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateMessageRequest $request)
    {
        $message = $this->messages->store($request);
        event(new MessageWasReceived($message));
        return redirect()
                    ->route('mensajes.create')
                    ->with('info', 'Tu mensaje ha sido enviado correctamente');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $message = $this->messages->findById($id);
        return view('messages.show', compact('message'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $message = $this->messages->findById($id);
        return view('messages.edit', compact('message'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CreateMessageRequest $request, $id)
    {
        $message = $this->messages->update($request, $id);
        // Redireccionar
        return redirect()
                    ->route('mensajes.index')
                    ->with('info', 'Tu mensaje ha sido modificado correctamente');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $message = $this->messages->destroy($id);
        return redirect()
                    ->route('mensajes.index')
                    ->with('info', 'Tu mensaje ha sido eliminado correctamente');
    }
}

resources/views/messages/create.blade.php
@extends('layout')

@section('contenido')
<h1>Contacto</h1>
<h2>Escríbeme</h2>
@if(session()->has('info'))
	<div class="alert alert-success" role="alert">
	  	{{ session('info') }}
	</div>
{{-- @else --}}
@endif
<form method="post" action="{{route('mensajes.store')}}">
	@include('messages.form', ['message' => new App\Message, 'stateFields' => Auth::guest()])
</form>
@stop

resources/views/messages/edit.blade.php
@extends('layout')

@section('contenido')
<h1>Contacto</h1>
<form method="post" action="{{route('mensajes.update', $message->id)}}">
	{{ method_field('PUT') }}
	@include('messages.form', ['btnText' => 'Modificar', 'stateFields' => !$message->user_id])
</form>
@stop

resources/views/messages/form.blade.php
{{-- Devuelve un input con el valor del _token --}}
{!! csrf_field() !!}
@if ($stateFields)
	<p><label for="nombre">
		Nombre
		<input class="form-control" type="text" name="nombre" value="{{ $message->nombre or old('nombre') }}">
		{!! $errors->first('nombre', '<span class="p-1 mb-1 bg-danger text-white">:message</span>') !!}
	</label></p>
	<p><label for="email">
		Email
		<input class="form-control" type="text" name="email" value="{{ $message->email or old('email') }}">
		{!! $errors->first('email', '<span class="p-1 mb-1 bg-danger text-white">:message</span>') !!}
	</label></p>
@endif
<p><label for="mensaje">
	Mensaje
	<textarea class="form-control" name="mensaje">{{ $message->mensaje or old('mensaje') }}</textarea>
	{!! $errors->first('mensaje', '<span class="p-1 mb-1 bg-danger text-white">:message</span>') !!}
</label></p>
<input type="submit" class="btn btn-primary" value="{{ $btnText or 'Enviar' }}">

{{-- Sintaxis --}}
{{-- PHP<7	: isset($a) ? $a : 0 --}}
{{-- PHP 7	: $a ?? 0 --}}
{{-- LARAVEL: $a or 0 --}}

resources/views/messages/index.blade.php
@extends('layout')

@section('contenido')

<h1>Lista de mensajes</h1>
@if(session()->has('info'))
	<div class="alert alert-success" role="alert">
	  	{{ session('info') }}
	</div>
@endif

@if(count($messages) > 0)
	<table class="table">
		<thead>
			<tr>
				<td>ID</td>
				<td>Nombre</td>
				<td>Email</td>
				<td>Mensaje</td>
				<td>Notas</td>
				<td>Etiquetas</td>
				<td>Teléfono</td>
				<td>Creado el</td>
				<td>Modificado el</td>
				<td>Acciones</td>
			</tr>
		</thead>
		<tbody>
		@foreach($messages as $message)
			<tr>
				<td>{{$message->id}}</td>
				
				<td>{{$message->present()->userName()}}</td>
				<td>{{$message->present()->userEmail()}}</td>

				<td>{{$message->present()->link()}}</td>
				<td>{{$message->present()->notes()}}</td>
				<td>{{$message->present()->tags()}}</td>
				<td>{{$message->phone}}</td>
				<td>{{$message->created_at}}</td>
				<td>{{$message->updated_at}}</td>
				<td>
					<a class="btn btn-info btn-sm" href="{{ route('mensajes.edit', $message->id) }}">Editar</a>
					<form style="display: inline;" action="{{ route('mensajes.destroy', $message->id) }}" method="POST">
						{{method_field('DELETE')}}
						{{csrf_field()}}
						<input type="submit" class="btn btn-danger btn-sm" value="Eliminar">
					</form>
				</td>
			</tr>
		@endforeach
		</tbody>
		{!! $messages->fragment('hash')->appends(request()->query())->links('pagination::bootstrap-4') !!}
	</table>
@else
	<p>No hay mensajes guardados</p>
@endif

@stop

resources/views/messages/show.blade.php
@extends('layout')

@section('contenido')
<h1>Mensaje {{$message->id}}</h1>
<p>Mensaje de {{$message->present()->userName()}} - {{$message->present()->userEmail()}}</p>
<p>{{$message->mensaje}}</p>
@stop